#ifndef MSCFINALPROJECT_RENDER_SPRITEMANAGER_HPP
#define MSCFINALPROJECT_RENDER_SPRITEMANAGER_HPP

namespace render::SpriteManager {
    void init();

}

#endif//MSCFINALPROJECT_RENDER_SPRITEMANAGER_HPP